name: Tests

on:
  push:
    # This should disable running the workflow on tags, according to the
    # on.<push|pull_request>.<branches|tags> GitHub Actions docs.
    branches:
      - "*"
  pull_request:
  schedule:
    - cron: '48 6 * * *'

concurrency:
  # Cancel older requests of the same workflow in the same branch.
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:

  linux:  # {{{
    runs-on: ubuntu-latest
    if: true

    strategy:
      fail-fast: false
      matrix:
        include:
          # Test different combinations of Python, Postgres, libpq.
          - {impl: python, python: "3.10", postgres: "postgres:14"}

    env:
      PSYCOPG_IMPL: ${{ matrix.impl }}
      DEPS: ./psycopg[test] ./psycopg_pool
      PSYCOPG_TEST_DSN: "host=127.0.0.1 user=postgres"
      PGPASSWORD: password
      MARKERS: ""
      TMNET_DEV_API_KEY: ${{ secrets.TMNET_DEV_API_KEY }}
      TMNET_API_KEY: ${{ secrets.TMNET_API_KEY }}

      # Enable to run tests using the minimum version of dependencies.
      # PIP_CONSTRAINT: ${{ github.workspace }}/tests/constraints.txt

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Run PostgreSQL
        # Note: this would love to be a service, but I don't see a way to pass
        # the args to the docker run command line.
        run: |
          docker pull ${{ matrix.postgres }}
          docker run --rm -d --name postgres -p 5432:5432 \
            -e POSTGRES_PASSWORD=password ${{ matrix.postgres }} \
            -c max_prepared_transactions=10

      - name: Install the newest libpq version available
        if: ${{ matrix.libpq == 'newest' }}
        run: |
          set -x

          curl -sL https://www.postgresql.org/media/keys/ACCC4CF8.asc \
            | gpg --dearmor \
            | sudo tee /etc/apt/trusted.gpg.d/apt.postgresql.org.gpg > /dev/null

          # NOTE: in order to test with a preview release, add its number to
          # the deb entry. For instance, to test on preview Postgres 16, use:
          # "deb http://apt.postgresql.org/pub/repos/apt ${rel}-pgdg main 16"
          rel=$(lsb_release -c -s)
          echo "deb http://apt.postgresql.org/pub/repos/apt ${rel}-pgdg main" \
            | sudo tee -a /etc/apt/sources.list.d/pgdg.list > /dev/null
          sudo apt-get -qq update

          pqver=$(apt-cache show libpq5  | grep ^Version: | head -1 \
            | awk '{print $2}')
          sudo apt-get -qq -y install "libpq-dev=${pqver}" "libpq5=${pqver}"

      - name: Install the oldest libpq version available
        if: ${{ matrix.libpq == 'oldest' }}
        run: |
          set -x
          pqver=$(apt-cache show libpq5  | grep ^Version: | tail -1 \
            | awk '{print $2}')
          sudo apt-get -qq -y --allow-downgrades install \
            "libpq-dev=${pqver}" "libpq5=${pqver}"

      - if: ${{ matrix.ext == 'dns' }}
        run: |
          echo "DEPS=$DEPS dnspython" >> $GITHUB_ENV
          echo "MARKERS=$MARKERS dns" >> $GITHUB_ENV

      - if: ${{ matrix.ext == 'postgis' }}
        run: |
          echo "DEPS=$DEPS shapely" >> $GITHUB_ENV
          echo "MARKERS=$MARKERS postgis" >> $GITHUB_ENV

      - if: ${{ matrix.impl == 'c' }}
        run: |
          echo "DEPS=$DEPS ./psycopg_c" >> $GITHUB_ENV

      - name: Install Python dependencies
        run: pip install --editable $DEPS --config-settings editable-mode=strict

      - name: Install pytest-testmon (commit-based)
        run: pip install pytest_testmon@git+https://github.com/tarpas/pytest-testmon.git@598930dfe1627fa241fe909abf053688d669ed4a#egg=pytest_testmon

      - name: Run tests
        run: ./tools/build/ci_test.sh


  # }}}
